id = "csharp-syntax"
name = "C# Syntax Highlighting"
version = "1.0.0"
schema_version = 1
authors = ["Derek Cunningham <cunninghamd@nosleep.ca>"]
description = "C# syntax highlighting for Zed"
repository = "https://github.com/cunninghamd/zed-c-sharp"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "cac6d5fb595f5811a076336682d5d595ac1c9e85"
